# Generated by Django 6.0.2 on 2026-02-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=255),
        ),
    ]
